"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserBase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNAME_FIELD_NUMBER: builtins.int
    FACE_FIELD_NUMBER: builtins.int
    uname: builtins.str
    face: builtins.str
    def __init__(
        self,
        *,
        uname: builtins.str = ...,
        face: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["face", b"face", "uname", b"uname"]) -> None: ...

global___UserBase = UserBase
