"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from . import base_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MedalInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_ID_FIELD_NUMBER: builtins.int
    INT2_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    COLOR_START_FIELD_NUMBER: builtins.int
    COLOR_END_FIELD_NUMBER: builtins.int
    COLOR_BORDER_FIELD_NUMBER: builtins.int
    ROOMID_FIELD_NUMBER: builtins.int
    INT4_FIELD_NUMBER: builtins.int
    target_id: builtins.int
    int2: builtins.int
    name: builtins.str
    color: builtins.int
    """maybe"""
    color_start: builtins.int
    color_end: builtins.int
    color_border: builtins.int
    roomid: builtins.int
    int4: builtins.int
    def __init__(
        self,
        *,
        target_id: builtins.int = ...,
        int2: builtins.int = ...,
        name: builtins.str = ...,
        color: builtins.int = ...,
        color_start: builtins.int = ...,
        color_end: builtins.int = ...,
        color_border: builtins.int = ...,
        roomid: builtins.int = ...,
        int4: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["color", b"color", "color_border", b"color_border", "color_end", b"color_end", "color_start", b"color_start", "int2", b"int2", "int4", b"int4", "name", b"name", "roomid", b"roomid", "target_id", b"target_id"]) -> None: ...

global___MedalInfo = MedalInfo

@typing.final
class UMedalInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    COLOR_START_FIELD_NUMBER: builtins.int
    COLOR_END_FIELD_NUMBER: builtins.int
    COLOR_BORDER_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    RUID_FIELD_NUMBER: builtins.int
    INT4_FIELD_NUMBER: builtins.int
    V2_MEDAL_COLOR_START_FIELD_NUMBER: builtins.int
    V2_MEDAL_COLOR_END_FIELD_NUMBER: builtins.int
    V2_MEDAL_COLOR_BORDER_FIELD_NUMBER: builtins.int
    V2_MEDAL_TEXT_FIELD_NUMBER: builtins.int
    V2_MEDAL_LEVEL_FIELD_NUMBER: builtins.int
    name: builtins.str
    level: builtins.int
    color_start: builtins.int
    """maybe"""
    color_end: builtins.int
    color_border: builtins.int
    color: builtins.int
    id: builtins.int
    ruid: builtins.int
    int4: builtins.int
    """== MedalInfo.int4"""
    v2_medal_color_start: builtins.str
    """maybe"""
    v2_medal_color_end: builtins.str
    v2_medal_color_border: builtins.str
    v2_medal_text: builtins.str
    v2_medal_level: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        level: builtins.int = ...,
        color_start: builtins.int = ...,
        color_end: builtins.int = ...,
        color_border: builtins.int = ...,
        color: builtins.int = ...,
        id: builtins.int = ...,
        ruid: builtins.int = ...,
        int4: builtins.int = ...,
        v2_medal_color_start: builtins.str = ...,
        v2_medal_color_end: builtins.str = ...,
        v2_medal_color_border: builtins.str = ...,
        v2_medal_text: builtins.str = ...,
        v2_medal_level: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["color", b"color", "color_border", b"color_border", "color_end", b"color_end", "color_start", b"color_start", "id", b"id", "int4", b"int4", "level", b"level", "name", b"name", "ruid", b"ruid", "v2_medal_color_border", b"v2_medal_color_border", "v2_medal_color_end", b"v2_medal_color_end", "v2_medal_color_start", b"v2_medal_color_start", "v2_medal_level", b"v2_medal_level", "v2_medal_text", b"v2_medal_text"]) -> None: ...

global___UMedalInfo = UMedalInfo

@typing.final
class InteractWordUserInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Message1(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INT1_FIELD_NUMBER: builtins.int
        int1: builtins.int
        def __init__(
            self,
            *,
            int1: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["int1", b"int1"]) -> None: ...

    UID_FIELD_NUMBER: builtins.int
    BASE_FIELD_NUMBER: builtins.int
    MEDAL_INFO_FIELD_NUMBER: builtins.int
    MESSAGE1_FIELD_NUMBER: builtins.int
    STRING1_FIELD_NUMBER: builtins.int
    uid: builtins.int
    string1: builtins.str
    @property
    def base(self) -> base_pb2.UserBase: ...
    @property
    def medal_info(self) -> global___UMedalInfo:
        """可能同 指定用户的所有粉丝勋章信息 data.list[n].uinfo_medal"""

    @property
    def message1(self) -> global___InteractWordUserInfo.Message1: ...
    def __init__(
        self,
        *,
        uid: builtins.int = ...,
        base: base_pb2.UserBase | None = ...,
        medal_info: global___UMedalInfo | None = ...,
        message1: global___InteractWordUserInfo.Message1 | None = ...,
        string1: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["base", b"base", "medal_info", b"medal_info", "message1", b"message1"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["base", b"base", "medal_info", b"medal_info", "message1", b"message1", "string1", b"string1", "uid", b"uid"]) -> None: ...

global___InteractWordUserInfo = InteractWordUserInfo

@typing.final
class ActivateMessage(google.protobuf.message.Message):
    """example:
       https://i0.hdslb.com/bfs/live/bb88734558c6383a4cfb5fa16c9749d5290d95e8.png
       曾经活跃过，近期与你互动较少
       4
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICON_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    icon: builtins.str
    msg: builtins.str
    type: builtins.int
    def __init__(
        self,
        *,
        icon: builtins.str = ...,
        msg: builtins.str = ...,
        type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["icon", b"icon", "msg", b"msg", "type", b"type"]) -> None: ...

global___ActivateMessage = ActivateMessage

@typing.final
class InteractWordV2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    UNAME_FIELD_NUMBER: builtins.int
    STRING1_FIELD_NUMBER: builtins.int
    MSG_TYPE_FIELD_NUMBER: builtins.int
    ROOMID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    TIMESTAMP_MILLISECOND_FIELD_NUMBER: builtins.int
    MEDAL_INFO_FIELD_NUMBER: builtins.int
    STRING2_FIELD_NUMBER: builtins.int
    INT2_FIELD_NUMBER: builtins.int
    INT3_FIELD_NUMBER: builtins.int
    STRING4_FIELD_NUMBER: builtins.int
    USER_INFO_FIELD_NUMBER: builtins.int
    ACTIVATE_MESSAGE_FIELD_NUMBER: builtins.int
    uid: builtins.int
    uname: builtins.str
    string1: builtins.str
    msg_type: builtins.int
    roomid: builtins.int
    timestamp: builtins.int
    timestamp_millisecond: builtins.int
    string2: builtins.str
    int2: builtins.int
    int3: builtins.int
    string4: builtins.str
    @property
    def medal_info(self) -> global___MedalInfo: ...
    @property
    def user_info(self) -> global___InteractWordUserInfo: ...
    @property
    def activate_message(self) -> global___ActivateMessage:
        """relation_tain in issue#1100"""

    def __init__(
        self,
        *,
        uid: builtins.int = ...,
        uname: builtins.str = ...,
        string1: builtins.str = ...,
        msg_type: builtins.int = ...,
        roomid: builtins.int = ...,
        timestamp: builtins.int = ...,
        timestamp_millisecond: builtins.int = ...,
        medal_info: global___MedalInfo | None = ...,
        string2: builtins.str = ...,
        int2: builtins.int = ...,
        int3: builtins.int = ...,
        string4: builtins.str = ...,
        user_info: global___InteractWordUserInfo | None = ...,
        activate_message: global___ActivateMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["activate_message", b"activate_message", "medal_info", b"medal_info", "user_info", b"user_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["activate_message", b"activate_message", "int2", b"int2", "int3", b"int3", "medal_info", b"medal_info", "msg_type", b"msg_type", "roomid", b"roomid", "string1", b"string1", "string2", b"string2", "string4", b"string4", "timestamp", b"timestamp", "timestamp_millisecond", b"timestamp_millisecond", "uid", b"uid", "uname", b"uname", "user_info", b"user_info"]) -> None: ...

global___InteractWordV2 = InteractWordV2
