"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from . import base_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GuardInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GUARD_LEVEL_FIELD_NUMBER: builtins.int
    EXPIRE_TIME_FIELD_NUMBER: builtins.int
    guard_level: builtins.int
    expire_time: builtins.str
    def __init__(
        self,
        *,
        guard_level: builtins.int = ...,
        expire_time: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["expire_time", b"expire_time", "guard_level", b"guard_level"]) -> None: ...

global___GuardInfo = GuardInfo

@typing.final
class UserBase2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNAME_FIELD_NUMBER: builtins.int
    FACE_FIELD_NUMBER: builtins.int
    USER_BASE1_FIELD_NUMBER: builtins.int
    USER_BASE2_FIELD_NUMBER: builtins.int
    uname: builtins.str
    face: builtins.str
    @property
    def user_base1(self) -> base_pb2.UserBase: ...
    @property
    def user_base2(self) -> base_pb2.UserBase: ...
    def __init__(
        self,
        *,
        uname: builtins.str = ...,
        face: builtins.str = ...,
        user_base1: base_pb2.UserBase | None = ...,
        user_base2: base_pb2.UserBase | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user_base1", b"user_base1", "user_base2", b"user_base2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["face", b"face", "uname", b"uname", "user_base1", b"user_base1", "user_base2", b"user_base2"]) -> None: ...

global___UserBase2 = UserBase2

@typing.final
class OnlineRankUserInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    USER_BASE_FIELD_NUMBER: builtins.int
    GUARD_INFO_FIELD_NUMBER: builtins.int
    uid: builtins.int
    @property
    def user_base(self) -> global___UserBase2: ...
    @property
    def guard_info(self) -> global___GuardInfo: ...
    def __init__(
        self,
        *,
        uid: builtins.int = ...,
        user_base: global___UserBase2 | None = ...,
        guard_info: global___GuardInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["guard_info", b"guard_info", "user_base", b"user_base"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["guard_info", b"guard_info", "uid", b"uid", "user_base", b"user_base"]) -> None: ...

global___OnlineRankUserInfo = OnlineRankUserInfo

@typing.final
class OnlineRankV3Data(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    FACE_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    UNAME_FIELD_NUMBER: builtins.int
    RANK_FIELD_NUMBER: builtins.int
    BEFORE_RANK_FIELD_NUMBER: builtins.int
    USER_INFO_FIELD_NUMBER: builtins.int
    uid: builtins.int
    face: builtins.str
    score: builtins.str
    uname: builtins.str
    rank: builtins.int
    before_rank: builtins.int
    @property
    def user_info(self) -> global___OnlineRankUserInfo: ...
    def __init__(
        self,
        *,
        uid: builtins.int = ...,
        face: builtins.str = ...,
        score: builtins.str = ...,
        uname: builtins.str = ...,
        rank: builtins.int = ...,
        before_rank: builtins.int | None = ...,
        user_info: global___OnlineRankUserInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_before_rank", b"_before_rank", "before_rank", b"before_rank", "user_info", b"user_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_before_rank", b"_before_rank", "before_rank", b"before_rank", "face", b"face", "rank", b"rank", "score", b"score", "uid", b"uid", "uname", b"uname", "user_info", b"user_info"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_before_rank", b"_before_rank"]) -> typing.Literal["before_rank"] | None: ...

global___OnlineRankV3Data = OnlineRankV3Data

@typing.final
class OnlineRankV3(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CMD_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    cmd: builtins.str
    """online_rank"""
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OnlineRankV3Data]: ...
    def __init__(
        self,
        *,
        cmd: builtins.str = ...,
        data: collections.abc.Iterable[global___OnlineRankV3Data] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cmd", b"cmd", "data", b"data"]) -> None: ...

global___OnlineRankV3 = OnlineRankV3
