# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OnlineRankV3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'OnlineRankV3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12OnlineRankV3.proto\x12\x04\x62ili\x1a\nbase.proto\"5\n\tGuardInfo\x12\x13\n\x0bguard_level\x18\x01 \x01(\r\x12\x13\n\x0b\x65xpire_time\x18\x02 \x01(\t\"p\n\tUserBase2\x12\r\n\x05uname\x18\x01 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x01(\t\x12\"\n\nuser_base1\x18\x05 \x01(\x0b\x32\x0e.bili.UserBase\x12\"\n\nuser_base2\x18\x06 \x01(\x0b\x32\x0e.bili.UserBase\"j\n\x12OnlineRankUserInfo\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\"\n\tuser_base\x18\x02 \x01(\x0b\x32\x0f.bili.UserBase2\x12#\n\nguard_info\x18\x06 \x01(\x0b\x32\x0f.bili.GuardInfo\"\xb0\x01\n\x10OnlineRankV3Data\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\t\x12\r\n\x05uname\x18\x04 \x01(\t\x12\x0c\n\x04rank\x18\x05 \x01(\x05\x12\x18\n\x0b\x62\x65\x66ore_rank\x18\x06 \x01(\x05H\x00\x88\x01\x01\x12+\n\tuser_info\x18\x08 \x01(\x0b\x32\x18.bili.OnlineRankUserInfoB\x0e\n\x0c_before_rank\"A\n\x0cOnlineRankV3\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12$\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x16.bili.OnlineRankV3Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OnlineRankV3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUARDINFO']._serialized_start=40
  _globals['_GUARDINFO']._serialized_end=93
  _globals['_USERBASE2']._serialized_start=95
  _globals['_USERBASE2']._serialized_end=207
  _globals['_ONLINERANKUSERINFO']._serialized_start=209
  _globals['_ONLINERANKUSERINFO']._serialized_end=315
  _globals['_ONLINERANKV3DATA']._serialized_start=318
  _globals['_ONLINERANKV3DATA']._serialized_end=494
  _globals['_ONLINERANKV3']._serialized_start=496
  _globals['_ONLINERANKV3']._serialized_end=561
# @@protoc_insertion_point(module_scope)
